development:
  adapter: postgresql
  encoding: unicode
  database: dragthem
  pool: 5
  username: ubuntu
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: dragthem_test
  pool: 5
  username: ubuntu
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: dragthem_prod
  pool: 5
  username: ubuntu
  password: root